# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(216, 244)
        About.setMinimumSize(QtCore.QSize(216, 244))
        About.setMaximumSize(QtCore.QSize(216, 244))
        self.pushButton = QtWidgets.QPushButton(About)
        self.pushButton.setGeometry(QtCore.QRect(70, 210, 81, 31))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(About)
        self.label.setGeometry(QtCore.QRect(70, 40, 81, 81))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/img/icon.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(About)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 181, 31))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(About)
        self.label_3.setGeometry(QtCore.QRect(10, 160, 191, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(About)
        self.label_4.setGeometry(QtCore.QRect(30, 125, 151, 31))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(About)
        self.label_5.setGeometry(QtCore.QRect(20, 180, 171, 21))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(About)
        self.pushButton.clicked.connect(About.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "About"))
        self.pushButton.setText(_translate("About", "OK"))
        self.label_2.setText(_translate("About", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; vertical-align:super;\">M3U8 Converter</span></p></body></html>"))
        self.label_3.setText(_translate("About", "Copyright © 2022 h0fnar"))
        self.label_4.setText(_translate("About", "Version 1.0.1"))
        self.label_5.setText(_translate("About", "h0fnar@protonmail.com"))
import resources_rc
